export enum CardTypes {
  Tower = 'Башня',
  Priestess = 'Верховная жрица',
  Lovers = 'Влюбленные',
  Devil = 'Дьявол',
  Star = 'Звезда',
  Hierofant = 'Иерофант',
  Imperor = 'Император',
  Impress = 'Императрица',
  Chariot = 'Колесница',
  Fortune = 'Колесо фортуны',
  Moon = 'Луна',
  Mage = 'Маг',
  World = 'Мир',
  Hermit = 'Отшельник',
  Hanged = 'Повешенный',
  Strength = 'Сила',
  Death = 'Смерть',
  Sun = 'Солнце',
  Justice = 'Справедливость',
  Judgment = 'Суд',
  Temperance = 'Умеренность',
  Jester = 'Шут'
}